apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    environment: development
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: quality
  labels:
    environment: quality
    
---

apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    
